<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>use_Cart_use--even</name>
   <tag></tag>
   <elementGuidId>e16d5cbe-0e17-4a0a-802b-f10b6485e666</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//svg[contains(@class,'Icon Icon--cart')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>use</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>use--even</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xlink:href</name>
      <type>Main</type>
      <value>/assets/ui-icons.svg#cart-icon--even</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1676597138341_107&quot;)/header[@class=&quot;Header Header--top&quot;]/div[@class=&quot;Header-inner Header-inner--top&quot;]/div[3]/a[@class=&quot;Cart sqs-custom-cart sqs-template-integrated-shopping-cart&quot;]/span[@class=&quot;Cart-inner&quot;]/svg[@class=&quot;Icon Icon--cart&quot;]/use[@class=&quot;use--even&quot;]</value>
   </webElementProperties>
</WebElementEntity>
