<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Shareables_select template</name>
   <tag></tag>
   <elementGuidId>9c63b7c3-68af-4dba-818d-ff2594271cd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-view']/div/ui-view/section/md-content/md-content/ui-view/react-shareables/div/div[2]/div[2]/div/div/div[3]/div[2]/div/div[3]/div[2]/div/div[2]/div/div[2]/div/div/div/button/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.jss466</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root jss466</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-view&quot;)/div[1]/ui-view[@class=&quot;ng-scope&quot;]/section[@class=&quot;loggedin-wrapper ng-scope layout-row flex sticky-content&quot;]/md-content[@class=&quot;header-content-wrap _md&quot;]/md-content[@class=&quot;content-wrap _md&quot;]/ui-view[@class=&quot;ng-scope&quot;]/react-shareables[@class=&quot;ng-scope&quot;]/div[@class=&quot;MuiBox-root jss19 sc-dUjcNx fDgcnQ&quot;]/div[@class=&quot;MuiBox-root jss62&quot;]/div[@class=&quot;MuiBox-root jss235&quot;]/div[@class=&quot;MuiBox-root jss236&quot;]/div[@class=&quot;MuiBox-root jss237&quot;]/div[@class=&quot;MuiBox-root jss264&quot;]/div[@class=&quot;MuiBox-root jss279&quot;]/div[@class=&quot;MuiBox-root jss280&quot;]/div[@class=&quot;MuiBox-root jss333&quot;]/div[@class=&quot;MuiBox-root jss335&quot;]/div[@class=&quot;MuiBox-root jss336&quot;]/div[@class=&quot;MuiBox-root jss338&quot;]/div[@class=&quot;MuiBox-root jss339&quot;]/div[@class=&quot;MuiBox-root jss462&quot;]/div[@class=&quot;MuiBox-root jss463&quot;]/div[@class=&quot;MuiBox-root jss464&quot;]/div[@class=&quot;MuiBox-root jss465&quot;]/button[@class=&quot;MuiButtonBase-root&quot;]/div[1]/div[@class=&quot;MuiBox-root jss466&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-view']/div/ui-view/section/md-content/md-content/ui-view/react-shareables/div/div[2]/div[2]/div/div/div[3]/div[2]/div/div[3]/div[2]/div/div[2]/div/div[2]/div/div/div/button/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button/div/div</value>
   </webElementXpaths>
</WebElementEntity>
