<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Shareables_LHMD_Add_button</name>
   <tag></tag>
   <elementGuidId>6f9b32fa-3ad1-43c7-ad06-6ddc65a9bd47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-view']/div/ui-view/section/md-content/md-content/ui-view/react-shareables/div/div[2]/div[2]/div/div/div[3]/div[2]/div/div[2]/div[2]/div/nav/div/div/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.MuiButtonBase-root.MuiButton-root.MuiButton-contained.sc-jzJRlG.cPUFPc.MuiButton-containedPrimary.MuiButton-fullWidth</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiButton-root MuiButton-contained sc-jzJRlG cPUFPc MuiButton-containedPrimary MuiButton-fullWidth</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>theme</name>
      <type>Main</type>
      <value>[object Object]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-view&quot;)/div[1]/ui-view[@class=&quot;ng-scope&quot;]/section[@class=&quot;loggedin-wrapper ng-scope layout-row flex sticky-content&quot;]/md-content[@class=&quot;header-content-wrap _md&quot;]/md-content[@class=&quot;content-wrap _md&quot;]/ui-view[@class=&quot;ng-scope&quot;]/react-shareables[@class=&quot;ng-scope&quot;]/div[@class=&quot;MuiBox-root jss19 sc-dUjcNx fDgcnQ&quot;]/div[@class=&quot;MuiBox-root jss62&quot;]/div[@class=&quot;MuiBox-root jss251&quot;]/div[@class=&quot;MuiBox-root jss252&quot;]/div[@class=&quot;MuiBox-root jss253&quot;]/div[@class=&quot;MuiBox-root jss280&quot;]/div[@class=&quot;MuiBox-root jss295&quot;]/div[@class=&quot;MuiBox-root jss296&quot;]/div[@class=&quot;MuiBox-root jss327&quot;]/div[@class=&quot;MuiBox-root jss329&quot;]/div[@class=&quot;MuiBox-root jss452&quot;]/nav[@class=&quot;MuiList-root sc-hqyNC fxVdCF MuiList-padding&quot;]/div[@class=&quot;MuiBox-root jss724&quot;]/div[1]/div[@class=&quot;MuiBox-root jss725&quot;]/div[@class=&quot;MuiBox-root jss727&quot;]/a[@class=&quot;MuiButtonBase-root MuiButton-root MuiButton-contained sc-jzJRlG cPUFPc MuiButton-containedPrimary MuiButton-fullWidth&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-view']/div/ui-view/section/md-content/md-content/ui-view/react-shareables/div/div[2]/div[2]/div/div/div[3]/div[2]/div/div[2]/div[2]/div/nav/div/div/div/div[2]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a template:'])[1]/following::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Local Housing Market Data'])[1]/following::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Irvine, CA'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
   </webElementXpaths>
</WebElementEntity>
