<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ListPacks_MuiBox-root jss1181</name>
   <tag></tag>
   <elementGuidId>2240324c-7f63-48d8-af53-629131831098</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-view']/div/ui-view/section/md-content/md-content/ui-view/react-shareables-library/div/div/div[2]/div[3]/div/div/div[6]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.jss1181</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root jss1181</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-view&quot;)/div[1]/ui-view[@class=&quot;ng-scope&quot;]/section[@class=&quot;loggedin-wrapper ng-scope layout-row flex sticky-content&quot;]/md-content[@class=&quot;header-content-wrap _md&quot;]/md-content[@class=&quot;content-wrap _md&quot;]/ui-view[@class=&quot;ng-scope&quot;]/react-shareables-library[@class=&quot;ng-scope&quot;]/div[@class=&quot;MuiBox-root jss882 sc-bHwgHz gfuHXi&quot;]/div[@class=&quot;MuiBox-root jss883&quot;]/div[@class=&quot;MuiBox-root jss972 sc-itybZL drZuUW&quot;]/div[@class=&quot;MuiBox-root jss1023 sc-fzsDOv eahecb&quot;]/div[@class=&quot;MuiBox-root jss1024 sc-fONwsr cXkbTI&quot;]/div[@class=&quot;MuiBox-root jss1169 sc-giadOv fyIgNo hide-scrollbar&quot;]/div[@class=&quot;MuiBox-root jss1180&quot;]/div[@class=&quot;MuiBox-root jss1181&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-view']/div/ui-view/section/md-content/md-content/ui-view/react-shareables-library/div/div/div[2]/div[3]/div/div/div[6]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[6]/div</value>
   </webElementXpaths>
</WebElementEntity>
