<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ListReports Blue (Default)Baird  War_f7482d</name>
   <tag></tag>
   <elementGuidId>0714d286-3948-403a-a598-ac6991d5bc69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;color_theme&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='color_theme']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>color_theme</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vm.model.colorTheme</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-valid ng-touched ng-dirty ng-valid-parse</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>opt.id as opt.name group by opt.group for opt in vm.model.colorThemes | orderBy:['group_order', 'name']</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>vm.events.onColorThemeChange(vm.model.colorTheme)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ListReports Blue (Default)Baird &amp; WarnerBerkshire Hathaway Home ServicesBetter Homes and GardensCentury 21Climb SFColdwell BankerCompassCorcoranERA Real Estate (Grey)ERA Real Estate (Red)eXp RealtyHomebridgeHomeSmartIron Valley RealtorsJ. Rockcliff RealtorsJack Conway RealtorsKeller Williams RealtyNextHomePrudential (Dark)Prudential (Light)RE MAXRealty One GroupResidential Properties, LtdSerenoSeven Gables Real EstateSotheby's International RealtySummaWatson Realty Corp.WeichertWilliam RaveisWilliams &amp; StuartBlue 1: MidnightBlue 2: Smurf VillageBlue 3: Blue CrushBlue 4: Blue SteelBlue 5: MarinaBlue 6: Dodger BlueBlue 7: NavyBlue 8: HeisenbergBlue 9: IndigoRed 1: MagnetoRed 2: MaroonedRed 3: Kool-AidRed 4: TarantinoRed 5: LifeguardRed 6: StrawberryRed 7: FreedomRed 8: Deck the HallsGreen 1: Sherwood ForestGreen 2: Mineral GreenGreen 3: MintGreen 4: WatermelonGreen 5: Deck the Halls (Green)Purple 1: Very BerryPurple 2: Joker's JacketPurple 3: Lakers' PurpleBrown 1: OrganicBrown 2: MochaBrown 3: MojaveOrange 1: Orange is the New BlackOrange 2: Old Towne OrangeOrange 3: Mid-Century OrangeOrange 4: Pumpkin SpiceOrange 5: Orange JuicePink 1: Passion Fruit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-view&quot;)/div[1]/ui-view[@class=&quot;ng-scope&quot;]/section[@class=&quot;loggedin-wrapper ng-scope layout-row flex&quot;]/md-content[@class=&quot;header-content-wrap _md&quot;]/md-content[@class=&quot;content-wrap _md&quot;]/ui-view[@class=&quot;ng-scope&quot;]/settings[@class=&quot;ng-scope&quot;]/section[1]/tabbar[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;tabbar-content flex&quot;]/section[@class=&quot;listreports-settings ng-scope&quot;]/settings-listreports-settings[1]/div[@class=&quot;group group-item&quot;]/div[1]/div[@class=&quot;form-group&quot;]/select[@class=&quot;form-control ng-valid ng-touched ng-dirty ng-valid-parse&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='color_theme']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-view']/div/ui-view/section/md-content/md-content/ui-view/settings/section/tabbar/div[2]/section/settings-listreports-settings/div/div/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default color theme'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View color options'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of Use'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
   </webElementXpaths>
</WebElementEntity>
