<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>polygon</name>
   <tag></tag>
   <elementGuidId>7fba1442-fa9d-4900-bb93-913503d442d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>polygon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>polygon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill-rule</name>
      <type>Main</type>
      <value>evenodd</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clip-rule</name>
      <type>Main</type>
      <value>evenodd</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#FFFFFF</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>points</name>
      <type>Main</type>
      <value>53,22 53,58 79,40</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w-vulcan-v2-99&quot;)/div[@class=&quot;w-vulcan-overlays-table w-css-reset&quot;]/div[@class=&quot;w-vulcan-overlays--center w-css-reset&quot;]/div[@class=&quot;w-css-reset&quot;]/div[@class=&quot;w-css-reset&quot;]/div[@class=&quot;w-bpb-wrapper w-css-reset w-css-reset-tree&quot;]/button[@class=&quot;w-big-play-button w-css-reset-button-important w-vulcan-v2-button&quot;]/svg[1]/polygon[1]</value>
   </webElementProperties>
</WebElementEntity>
