<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DOM_jss2919</name>
   <tag></tag>
   <elementGuidId>a4a9acd9-021b-4ef6-bec1-3182496181d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.jss2953 > span.MuiButtonBase-root.MuiIconButton-root.jss2916.MuiCheckbox-root.jss2906 > span.MuiIconButton-label > input.jss2919</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='LHcza8IILD4Nf80c7ER0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss2919</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-indeterminate</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>LHcza8IILD4Nf80c7ER0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-view&quot;)/div[1]/ui-view[@class=&quot;ng-scope&quot;]/section[@class=&quot;loggedin-wrapper ng-scope layout-row flex&quot;]/md-content[@class=&quot;header-content-wrap _md&quot;]/md-content[@class=&quot;content-wrap _md&quot;]/ui-view[@class=&quot;ng-scope&quot;]/react-list-packs[@class=&quot;ng-scope&quot;]/div[@class=&quot;MuiBox-root jss2607&quot;]/div[2]/div[@class=&quot;MuiBox-root jss2675&quot;]/div[@class=&quot;MuiBox-root jss2680&quot;]/div[@class=&quot;MuiBox-root jss2783&quot;]/div[@class=&quot;MuiBox-root jss2784&quot;]/div[@class=&quot;MuiBox-root jss2833&quot;]/div[@class=&quot;MuiBox-root jss2901&quot;]/div[@class=&quot;MuiBox-root jss2902&quot;]/table[@class=&quot;sc-iyvyFf ccBVHD&quot;]/tbody[@class=&quot;sc-kfGgVZ eravuG&quot;]/tr[@class=&quot;sc-esjQYD jAVbai&quot;]/td[@class=&quot;sc-eXEjpC jYgZj&quot;]/div[@class=&quot;MuiBox-root jss2953&quot;]/span[@class=&quot;MuiButtonBase-root MuiIconButton-root jss2916 MuiCheckbox-root jss2906&quot;]/span[@class=&quot;MuiIconButton-label&quot;]/input[@class=&quot;jss2919&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='LHcza8IILD4Nf80c7ER0']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-view']/div/ui-view/section/md-content/md-content/ui-view/react-list-packs/div[2]/div[2]/div/div[2]/div[3]/div/div[2]/div/div/table/tbody/tr/td/div/span/span/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/span/span/input</value>
   </webElementXpaths>
</WebElementEntity>
