<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_DOM_jss2907 jss2954 jss2908</name>
   <tag></tag>
   <elementGuidId>c0454bf2-bc4e-461b-bc31-61385ecfe393</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.jss2907.jss2954.jss2908</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-view']/div/ui-view/section/md-content/md-content/ui-view/react-list-packs/div[2]/div[2]/div/div[2]/div[3]/div/div[2]/div/div/table/tbody/tr/td/div/span/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss2907 jss2954 jss2908</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-size</name>
      <type>Main</type>
      <value>default</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-view&quot;)/div[1]/ui-view[@class=&quot;ng-scope&quot;]/section[@class=&quot;loggedin-wrapper ng-scope layout-row flex&quot;]/md-content[@class=&quot;header-content-wrap _md&quot;]/md-content[@class=&quot;content-wrap _md&quot;]/ui-view[@class=&quot;ng-scope&quot;]/react-list-packs[@class=&quot;ng-scope&quot;]/div[@class=&quot;MuiBox-root jss2607&quot;]/div[2]/div[@class=&quot;MuiBox-root jss2675&quot;]/div[@class=&quot;MuiBox-root jss2680&quot;]/div[@class=&quot;MuiBox-root jss2783&quot;]/div[@class=&quot;MuiBox-root jss2784&quot;]/div[@class=&quot;MuiBox-root jss2833&quot;]/div[@class=&quot;MuiBox-root jss2901&quot;]/div[@class=&quot;MuiBox-root jss2902&quot;]/table[@class=&quot;sc-iyvyFf ccBVHD&quot;]/tbody[@class=&quot;sc-kfGgVZ eravuG&quot;]/tr[@class=&quot;sc-esjQYD jAVbai&quot;]/td[@class=&quot;sc-eXEjpC jYgZj&quot;]/div[@class=&quot;MuiBox-root jss2953&quot;]/span[@class=&quot;MuiButtonBase-root MuiIconButton-root jss2916 MuiCheckbox-root jss2906 jss2917 Mui-checked&quot;]/span[@class=&quot;MuiIconButton-label&quot;]/span[@class=&quot;jss2907 jss2954 jss2908&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-view']/div/ui-view/section/md-content/md-content/ui-view/react-list-packs/div[2]/div[2]/div/div[2]/div[3]/div/div[2]/div/div/table/tbody/tr/td/div/span/span/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/span/span/span</value>
   </webElementXpaths>
</WebElementEntity>
