<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Notable to Share Option 2</name>
   <tag></tag>
   <elementGuidId>d87ee581-497d-4e85-a2e9-369f9919fdd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.jss291</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/button/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root jss291</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-view&quot;)/div[1]/ui-view[@class=&quot;ng-scope&quot;]/section[@class=&quot;loggedin-wrapper ng-scope layout-row flex sticky-content&quot;]/md-content[@class=&quot;header-content-wrap _md&quot;]/md-content[@class=&quot;content-wrap _md&quot;]/ui-view[@class=&quot;ng-scope&quot;]/react-shareables[@class=&quot;ng-scope&quot;]/div[@class=&quot;MuiBox-root jss19 sc-jVODtj jVFwUI&quot;]/div[@class=&quot;MuiBox-root jss62&quot;]/div[@class=&quot;MuiBox-root jss217&quot;]/div[@class=&quot;MuiBox-root jss218&quot;]/div[@class=&quot;MuiBox-root jss219&quot;]/div[@class=&quot;MuiBox-root jss259&quot;]/div[@class=&quot;MuiBox-root jss265&quot;]/div[@class=&quot;MuiBox-root jss266&quot;]/div[@class=&quot;MuiBox-root jss275 sc-gwVKww QhyL&quot;]/div[@class=&quot;MuiBox-root jss276&quot;]/div[@class=&quot;MuiBox-root jss277&quot;]/div[@class=&quot;MuiBox-root jss279&quot;]/div[@class=&quot;MuiBox-root jss280&quot;]/div[@class=&quot;MuiBox-root jss287&quot;]/div[@class=&quot;MuiBox-root jss288&quot;]/div[@class=&quot;MuiBox-root jss289&quot;]/button[@class=&quot;MuiButtonBase-root&quot;]/div[@class=&quot;MuiBox-root jss290 sc-bwCtUz FakHM&quot;]/div[@class=&quot;MuiBox-root jss291&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-view']/div/ui-view/section/md-content/md-content/ui-view/react-shareables/div/div[2]/div[2]/div/div/div[3]/div[2]/div/div[2]/div/div/div[2]/div/div[2]/div/div/button/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button/div/div</value>
   </webElementXpaths>
</WebElementEntity>
