<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Shareables Option 1</name>
   <tag></tag>
   <elementGuidId>d38d1990-83cd-443c-9d23-723854198d34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-view&quot;)/div[1]/ui-view[@class=&quot;ng-scope&quot;]/section[@class=&quot;loggedin-wrapper ng-scope layout-row flex sticky-content&quot;]/md-content[@class=&quot;header-content-wrap _md&quot;]/md-content[@class=&quot;content-wrap _md&quot;]/ui-view[@class=&quot;ng-scope&quot;]/react-shareables[@class=&quot;ng-scope&quot;]/div[@class=&quot;MuiBox-root jss19 sc-jVODtj jVFwUI&quot;]/div[@class=&quot;MuiBox-root jss62&quot;]/div[@class=&quot;MuiBox-root jss239&quot;]/div[@class=&quot;MuiBox-root jss240&quot;]/div[@class=&quot;MuiBox-root jss241&quot;]/div[@class=&quot;MuiBox-root jss268&quot;]/div[@class=&quot;MuiBox-root jss296&quot;]/div[@class=&quot;MuiBox-root jss297&quot;]/div[@class=&quot;MuiBox-root jss298&quot;]/div[@class=&quot;MuiBox-root jss300&quot;]/div[@class=&quot;MuiBox-root jss301&quot;]/div[@class=&quot;MuiBox-root jss303&quot;]/div[@class=&quot;MuiBox-root jss304&quot;]/div[@class=&quot;MuiBox-root jss305&quot;]/div[@class=&quot;MuiBox-root jss306&quot;]/div[@class=&quot;MuiBox-root jss307&quot;]/div[@class=&quot;MuiBox-root jss308&quot;]/button[@class=&quot;MuiButtonBase-root&quot;]/div[1]/div[3]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-view']/div/ui-view/section/md-content/md-content/ui-view/react-shareables/div/div[2]/div[2]/div/div/div[3]/div[2]/div/div/div[2]/div/div[2]/div/div/div/div/div/button/div/div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/div[3]</value>
   </webElementXpaths>
</WebElementEntity>
