<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Template 2</name>
   <tag></tag>
   <elementGuidId>d894bc8c-e257-40dc-a30e-2e0639d18a4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.jss316</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/button/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root jss316</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-view&quot;)/div[1]/ui-view[@class=&quot;ng-scope&quot;]/section[@class=&quot;loggedin-wrapper ng-scope layout-row flex sticky-content&quot;]/md-content[@class=&quot;header-content-wrap _md&quot;]/md-content[@class=&quot;content-wrap _md&quot;]/ui-view[@class=&quot;ng-scope&quot;]/react-shareables[@class=&quot;ng-scope&quot;]/div[@class=&quot;MuiBox-root jss19 sc-jVODtj jVFwUI&quot;]/div[@class=&quot;MuiBox-root jss62&quot;]/div[@class=&quot;MuiBox-root jss239&quot;]/div[@class=&quot;MuiBox-root jss240&quot;]/div[@class=&quot;MuiBox-root jss241&quot;]/div[@class=&quot;MuiBox-root jss289&quot;]/div[@class=&quot;MuiBox-root jss298&quot;]/div[@class=&quot;MuiBox-root jss299&quot;]/div[@class=&quot;MuiBox-root jss300&quot;]/div[@class=&quot;MuiBox-root jss302&quot;]/div[@class=&quot;MuiBox-root jss304&quot;]/div[@class=&quot;MuiBox-root jss305&quot;]/div[@class=&quot;MuiBox-root jss312&quot;]/div[@class=&quot;MuiBox-root jss313&quot;]/div[@class=&quot;MuiBox-root jss314&quot;]/button[@class=&quot;MuiButtonBase-root&quot;]/div[@class=&quot;MuiBox-root jss315 sc-bwCtUz FakHM&quot;]/div[@class=&quot;MuiBox-root jss316&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-view']/div/ui-view/section/md-content/md-content/ui-view/react-shareables/div/div[2]/div[2]/div/div/div[3]/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div/button/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button/div/div</value>
   </webElementXpaths>
</WebElementEntity>
