<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>polygon</name>
   <tag></tag>
   <elementGuidId>997e69fc-cbc2-4349-a734-67cdb1a6b92b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>polygon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>points</name>
      <type>Main</type>
      <value>11.556,7.5 0,15 0,0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w-vulcan-v2-99&quot;)/div[@class=&quot;w-bottom-bar w-css-reset&quot;]/div[@class=&quot;w-bottom-bar-lower w-css-reset&quot;]/div[@class=&quot;w-bottom-bar-left w-css-reset&quot;]/div[@class=&quot;w-bottom-bar-left-inner w-css-reset&quot;]/div[@class=&quot;w-css-reset&quot;]/div[@class=&quot;w-vulcan-button-wrapper w-css-reset&quot;]/button[@class=&quot;w-vulcan-v2-button w-css-reset w-css-reset-tree w-css-reset-button-important&quot;]/div[@class=&quot;w-vulcan-icon-wrapper&quot;]/div[1]/div[1]/div[2]/svg[@class=&quot;w-css-reset w-css-reset-tree&quot;]/polygon[1]</value>
   </webElementProperties>
</WebElementEntity>
