<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Send_jss411</name>
   <tag></tag>
   <elementGuidId>e1e46501-4e25-465e-9c51-733cf6b977ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.jss411</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss411</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-indeterminate</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-view&quot;)/div[1]/ui-view[@class=&quot;ng-scope&quot;]/section[@class=&quot;loggedin-wrapper ng-scope layout-row flex&quot;]/md-content[@class=&quot;header-content-wrap _md&quot;]/md-content[@class=&quot;content-wrap _md&quot;]/ui-view[@class=&quot;ng-scope&quot;]/react-listreports-live[@class=&quot;ng-scope&quot;]/div[@class=&quot;MuiBox-root jss2&quot;]/div[@class=&quot;MuiBox-root jss11&quot;]/div[@class=&quot;MuiBox-root jss15&quot;]/div[@class=&quot;MuiBox-root jss31&quot;]/div[@class=&quot;MuiBox-root jss46&quot;]/div[@class=&quot;MuiBox-root jss47&quot;]/div[@class=&quot;MuiBox-root jss48&quot;]/div[@class=&quot;MuiBox-root jss89&quot;]/div[@class=&quot;MuiBox-root jss129&quot;]/div[@class=&quot;MuiBox-root jss364&quot;]/div[@class=&quot;MuiBox-root jss386&quot;]/div[@class=&quot;MuiBox-root jss387&quot;]/div[@class=&quot;MuiBox-root jss390&quot;]/div[@class=&quot;MuiBox-root jss391&quot;]/label[@class=&quot;MuiFormControlLabel-root sc-jqCOkK kjfWVV&quot;]/span[@class=&quot;MuiButtonBase-root MuiIconButton-root jss408 MuiCheckbox-root jss392&quot;]/span[@class=&quot;MuiIconButton-label&quot;]/input[@class=&quot;jss411&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-view']/div/ui-view/section/md-content/md-content/ui-view/react-listreports-live/div/div[2]/div[2]/div/div/div/div/div[3]/div[2]/div/div[2]/div/div[3]/div[2]/label/span/span/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
   </webElementXpaths>
</WebElementEntity>
