<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Send_jss934</name>
   <tag></tag>
   <elementGuidId>9a9bf62d-daca-4158-9b56-a28478ebcf4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.jss934</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss934</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-indeterminate</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-view&quot;)/div[1]/ui-view[@class=&quot;ng-scope&quot;]/section[@class=&quot;loggedin-wrapper ng-scope layout-row flex&quot;]/md-content[@class=&quot;header-content-wrap _md&quot;]/md-content[@class=&quot;content-wrap _md&quot;]/ui-view[@class=&quot;ng-scope&quot;]/react-listreports-live[@class=&quot;ng-scope&quot;]/div[@class=&quot;MuiBox-root jss589&quot;]/div[@class=&quot;MuiBox-root jss598&quot;]/div[@class=&quot;MuiBox-root jss602&quot;]/div[@class=&quot;MuiBox-root jss618&quot;]/div[@class=&quot;MuiBox-root jss766&quot;]/div[@class=&quot;MuiBox-root jss767&quot;]/div[@class=&quot;MuiBox-root jss768&quot;]/div[@class=&quot;MuiBox-root jss809&quot;]/div[@class=&quot;MuiBox-root jss849&quot;]/div[@class=&quot;MuiBox-root jss850&quot;]/div[@class=&quot;MuiBox-root jss909&quot;]/div[@class=&quot;MuiBox-root jss910&quot;]/div[@class=&quot;MuiBox-root jss913&quot;]/div[@class=&quot;MuiBox-root jss914&quot;]/label[@class=&quot;MuiFormControlLabel-root sc-jqCOkK kjfWVV&quot;]/span[@class=&quot;MuiButtonBase-root MuiIconButton-root jss931 MuiCheckbox-root jss915&quot;]/span[@class=&quot;MuiIconButton-label&quot;]/input[@class=&quot;jss934&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-view']/div/ui-view/section/md-content/md-content/ui-view/react-listreports-live/div/div[2]/div[2]/div/div/div/div/div[3]/div[2]/div/div[2]/div/div[3]/div[2]/label/span/span/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
   </webElementXpaths>
</WebElementEntity>
