<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Send_jss172</name>
   <tag></tag>
   <elementGuidId>26400ceb-6bf9-407c-bf57-1de735a063a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.jss172</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss172</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-indeterminate</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-view&quot;)/div[1]/ui-view[@class=&quot;ng-scope&quot;]/section[@class=&quot;loggedin-wrapper ng-scope layout-row flex&quot;]/md-content[@class=&quot;header-content-wrap _md&quot;]/md-content[@class=&quot;content-wrap _md&quot;]/ui-view[@class=&quot;ng-scope&quot;]/react-listreports-live[@class=&quot;ng-scope&quot;]/div[@class=&quot;MuiBox-root jss2&quot;]/div[@class=&quot;MuiBox-root jss11&quot;]/div[@class=&quot;MuiBox-root jss12&quot;]/div[@class=&quot;MuiBox-root jss28&quot;]/div[@class=&quot;MuiBox-root jss43&quot;]/div[@class=&quot;MuiBox-root jss44&quot;]/div[@class=&quot;MuiBox-root jss45&quot;]/div[@class=&quot;MuiBox-root jss86&quot;]/div[@class=&quot;MuiBox-root jss87&quot;]/div[@class=&quot;MuiBox-root jss88&quot;]/div[@class=&quot;MuiBox-root jss147&quot;]/div[@class=&quot;MuiBox-root jss148&quot;]/div[@class=&quot;MuiBox-root jss151&quot;]/div[@class=&quot;MuiBox-root jss152&quot;]/label[@class=&quot;MuiFormControlLabel-root sc-jqCOkK kjfWVV&quot;]/span[@class=&quot;MuiButtonBase-root MuiIconButton-root jss169 MuiCheckbox-root jss153&quot;]/span[@class=&quot;MuiIconButton-label&quot;]/input[@class=&quot;jss172&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-view']/div/ui-view/section/md-content/md-content/ui-view/react-listreports-live/div/div[2]/div/div/div/div/div/div[3]/div/div/div[2]/div/div[3]/div[2]/label/span/span/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
   </webElementXpaths>
</WebElementEntity>
