<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_List_MuiGridListTile-imgFullHeight-1153</name>
   <tag></tag>
   <elementGuidId>8b7bbb2f-b5c0-4389-90f9-9c0ecf627290</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='14  Marthas Way ']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.MuiGridListTile-imgFullHeight-1153</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d1u2xbew1ldorh.cloudfront.net/unsafe/https%3A%2F%2Fdvvjkgh94f2v6.cloudfront.net%2F174ba08a%2FH6137965%2F83dcefb7.jpeg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>14  Marthas Way </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiGridListTile-imgFullHeight-1153</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiDialog-root-575 sc-eMRERa dIwtFB&quot;]/div[@class=&quot;MuiDialog-container-578 MuiDialog-scrollPaper-576&quot;]/div[@class=&quot;MuiPaper-root-633 MuiDialog-paper-579 MuiDialog-paperScrollPaper-580 MuiDialog-paperFullScreen-589 MuiPaper-elevation0-636 MuiPaper-rounded-634&quot;]/div[@class=&quot;MuiDialogContent-root-1145 sc-eqPNPO diOQKR&quot;]/div[@class=&quot;MuiBox-root-357 jss1188&quot;]/ul[@class=&quot;MuiGridList-root-1150 jss1187&quot;]/li[@class=&quot;MuiGridListTile-root-1151&quot;]/div[@class=&quot;MuiGridListTile-tile-1152 jss1185&quot;]/img[@class=&quot;MuiGridListTile-imgFullHeight-1153&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='14  Marthas Way ']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/img</value>
   </webElementXpaths>
</WebElementEntity>
