<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pool_fields.tags.with_pool</name>
   <tag></tag>
   <elementGuidId>4f4bf8e3-88d1-406e-b801-53216d8320dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='fields.tags.with_pool']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;fields.tags.with_pool&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss690 MuiSwitch-input-2598</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fields.tags.with_pool</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[11]/div[@class=&quot;MuiBox-root-357 jss2536&quot;]/div[1]/div[1]/div[@class=&quot;MuiBox-root-357 jss2569&quot;]/div[@class=&quot;MuiGrid-root-369 MuiGrid-container-370 MuiGrid-spacing-xs-2-393 MuiGrid-align-items-xs-center-378&quot;]/div[@class=&quot;MuiGrid-root-369 MuiGrid-container-370 MuiGrid-item-371 MuiGrid-justify-xs-space-between-389 MuiGrid-grid-xs-12-415 MuiGrid-grid-sm-8-425&quot;]/div[@class=&quot;MuiGrid-root-369 MuiGrid-container-370 MuiGrid-item-371 MuiGrid-align-items-xs-center-378 MuiGrid-grid-xs-12-415 MuiGrid-grid-sm-12-429&quot;]/div[@class=&quot;MuiGrid-root-369 MuiGrid-item-371 MuiGrid-grid-xs-2-405 MuiGrid-grid-sm-2-419&quot;]/div[@class=&quot;MuiBox-root-357 jss2588&quot;]/label[@class=&quot;MuiFormControlLabel-root-676&quot;]/span[@class=&quot;MuiSwitch-root-2589 sc-eQGPmX cbfJoG&quot;]/span[@class=&quot;MuiButtonBase-root-345 MuiIconButton-root-691 jss687 MuiSwitch-switchBase-2592 MuiSwitch-colorSecondary-2594&quot;]/span[@class=&quot;MuiIconButton-label-699&quot;]/input[@class=&quot;jss690 MuiSwitch-input-2598&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='fields.tags.with_pool']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/input</value>
   </webElementXpaths>
</WebElementEntity>
