<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User Id_MuiInputBase-input-105 MuiInp_648a8a</name>
   <tag></tag>
   <elementGuidId>0b3df3a9-92b9-49ba-9bb0-544e797ee89b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value> //div/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.MuiInputBase-input-105.MuiInput-input-278</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input-105 MuiInput-input-278</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;MuiBox-root-1 jss2&quot;]/div[@class=&quot;MuiBox-root-1 jss85&quot;]/div[@class=&quot;MuiBox-root-1 jss142&quot;]/div[@class=&quot;MuiGrid-root-143 MuiGrid-container-144 MuiGrid-align-items-xs-center-152 MuiGrid-justify-xs-center-161&quot;]/div[@class=&quot;MuiBox-root-1 jss246&quot;]/div[@class=&quot;MuiFormControl-root-90 MuiTextField-root-247&quot;]/div[@class=&quot;MuiInputBase-root-94 MuiInput-root-268 MuiInput-underline-273 Mui-focused Mui-focused MuiInputBase-formControl-95 MuiInput-formControl-269&quot;]/input[@class=&quot;MuiInputBase-input-105 MuiInput-input-278&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>N-VJAl8JaeZ</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[9]/div/div/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='N-VJAl8JaeZ']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='N-FdZ5ZKkQA']</value>
   </webElementXpaths>
</WebElementEntity>
