<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Interested</name>
   <tag></tag>
   <elementGuidId>e035dbe8-5730-42e9-93c7-ea898627fc6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Open house'])[1]/following::li[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.MuiButtonBase-root-345.MuiListItem-root-2837.MuiMenuItem-root-2833.tour-target-move-listing-card.MuiMenuItem-gutters-2834.MuiListItem-gutters-2844.MuiListItem-button-2845</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root-345 MuiListItem-root-2837 MuiMenuItem-root-2833 tour-target-move-listing-card MuiMenuItem-gutters-2834 MuiListItem-gutters-2844 MuiListItem-button-2845</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Interested</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiPopover-root-367&quot;]/div[@class=&quot;MuiPaper-root-633 MuiMenu-paper-1000 MuiPopover-paper-368 MuiPaper-elevation8-644 MuiPaper-rounded-634&quot;]/ul[@class=&quot;MuiList-root-2829 MuiMenu-list-1001 MuiList-padding-2830&quot;]/li[@class=&quot;MuiButtonBase-root-345 MuiListItem-root-2837 MuiMenuItem-root-2833 tour-target-move-listing-card MuiMenuItem-gutters-2834 MuiListItem-gutters-2844 MuiListItem-button-2845&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open house'])[1]/following::li[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Most square feet'])[1]/following::li[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]</value>
   </webElementXpaths>
</WebElementEntity>
