<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Los Cerritos Center, Cerritos, CA</name>
   <tag></tag>
   <elementGuidId>29f01fff-5346-4a11-9f08-f3140825f113</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='PlacesAutocomplete__suggestion-EiZMb3MgQ2Vycml0b3MgQ2VudGVyLCBDZXJyaXRvcywgQ0EsIFVTQSIuKiwKFAoSCbMBsEN0Ld2AEclYUwqi9sWJEhQKEglLOFv3AC3dgBEBPpPdSJVJDg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PlacesAutocomplete__suggestion-EiZMb3MgQ2Vycml0b3MgQ2VudGVyLCBDZXJyaXRvcywgQ0EsIFVTQSIuKiwKFAoSCbMBsEN0Ld2AEclYUwqi9sWJEhQKEglLOFv3AC3dgBEBPpPdSJVJDg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root-345 MuiListItem-root-1078 MuiMenuItem-root-1074 MuiMenuItem-gutters-1075 MuiListItem-gutters-1085 MuiListItem-button-1086</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PlacesAutocomplete__suggestion-EiZMb3MgQ2Vycml0b3MgQ2VudGVyLCBDZXJyaXRvcywgQ0EsIFVTQSIuKiwKFAoSCbMBsEN0Ld2AEclYUwqi9sWJEhQKEglLOFv3AC3dgBEBPpPdSJVJDg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Los Cerritos Center, Cerritos, CA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[11]/div[1]/ul[@class=&quot;MuiList-root-1070 MuiList-padding-1071&quot;]/li[@id=&quot;PlacesAutocomplete__suggestion-EiZMb3MgQ2Vycml0b3MgQ2VudGVyLCBDZXJyaXRvcywgQ0EsIFVTQSIuKiwKFAoSCbMBsEN0Ld2AEclYUwqi9sWJEhQKEglLOFv3AC3dgBEBPpPdSJVJDg&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='PlacesAutocomplete__suggestion-EiZMb3MgQ2Vycml0b3MgQ2VudGVyLCBDZXJyaXRvcywgQ0EsIFVTQSIuKiwKFAoSCbMBsEN0Ld2AEclYUwqi9sWJEhQKEglLOFv3AC3dgBEBPpPdSJVJDg']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::li[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::li[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
   </webElementXpaths>
</WebElementEntity>
