<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pending_MuiFab-label-565</name>
   <tag></tag>
   <elementGuidId>4d8d4dc6-12bf-45de-b95c-3d518db133f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='DLRU0EcXEUcR']/div[2]/div/div[2]/div/div[2]/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.MuiButtonBase-root-345.MuiFab-root-564.sc-fEUNkw.kyLTyS.card-move-button > span.MuiFab-label-565</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFab-label-565</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DLRU0EcXEUcR&quot;)/div[@class=&quot;tour-target-expanded-board-card tour-target-board-card&quot;]/div[@class=&quot;MuiBox-root-357 jss3461&quot;]/div[@class=&quot;MuiBox-root-357 jss3599&quot;]/div[@class=&quot;MuiBox-root-357 jss3600&quot;]/div[@class=&quot;MuiBox-root-357 jss3603&quot;]/div[@class=&quot;MuiBox-root-357 jss3604&quot;]/button[@class=&quot;MuiButtonBase-root-345 MuiFab-root-564 sc-fEUNkw kyLTyS card-move-button&quot;]/span[@class=&quot;MuiFab-label-565&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DLRU0EcXEUcR']/div[2]/div/div[2]/div/div[2]/div/button/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending'])[3]/following::span[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='🎉'])[3]/following::span[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/button/span</value>
   </webElementXpaths>
</WebElementEntity>
