<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Interested_MuiSvgIcon-root-348</name>
   <tag></tag>
   <elementGuidId>d9b7ff8f-452d-4993-bdb5-648aaffeac1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Deleted homes'])[1]/following::*[name()='svg'][3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root-357.jss789 > button.MuiButtonBase-root-345.MuiIconButton-root-691 > span.MuiIconButton-label-699 > svg.MuiSvgIcon-root-348</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiSvgIcon-root-348</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[2]/div[1]/div[@class=&quot;MuiBox-root-357 jss481&quot;]/div[1]/div[2]/div[@class=&quot;sc-RmnOB jVBuGP&quot;]/div[@class=&quot;MuiGrid-root-369 MuiGrid-container-370 MuiGrid-wrap-xs-nowrap-376 MuiGrid-align-items-xs-flex-start-379&quot;]/div[@class=&quot;Lane__Container-sc-1osreqb-0 jDcHWE&quot;]/div[@class=&quot;MuiGrid-root-369 Lane__StyledTitleWrapperGrid-sc-1osreqb-8 dCASdu MuiGrid-container-370 MuiGrid-align-items-xs-center-378 MuiGrid-justify-xs-space-between-389&quot;]/div[@class=&quot;MuiBox-root-357 jss788&quot;]/div[@class=&quot;MuiBox-root-357 jss789&quot;]/button[@class=&quot;MuiButtonBase-root-345 MuiIconButton-root-691&quot;]/span[@class=&quot;MuiIconButton-label-699&quot;]/svg[@class=&quot;MuiSvgIcon-root-348&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deleted homes'])[1]/following::*[name()='svg'][3]</value>
   </webElementXpaths>
</WebElementEntity>
