<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Invite</name>
   <tag></tag>
   <elementGuidId>1f66e420-f195-4d1e-af7b-280b069550d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-view']/div/ui-view/section/md-content/md-content/ui-view/react-arba/div/div/div/div/div/div[3]/div/div/div/div/nav/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.jss647</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root jss647</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invite</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-view&quot;)/div[1]/ui-view[@class=&quot;ng-scope&quot;]/section[@class=&quot;loggedin-wrapper ng-scope layout-row flex&quot;]/md-content[@class=&quot;header-content-wrap _md&quot;]/md-content[@class=&quot;content-wrap _md&quot;]/ui-view[@class=&quot;ng-scope&quot;]/react-arba[@class=&quot;ng-scope&quot;]/div[@class=&quot;MuiBox-root jss496 MuiBox-root jss495&quot;]/div[@class=&quot;MuiBox-root jss498&quot;]/div[@class=&quot;MuiBox-root jss499&quot;]/div[@class=&quot;MuiBox-root jss500&quot;]/div[@class=&quot;MuiBox-root jss501&quot;]/div[@class=&quot;MuiBox-root jss505&quot;]/div[@class=&quot;MuiBox-root jss506&quot;]/div[@class=&quot;MuiBox-root jss516&quot;]/div[@class=&quot;MuiBox-root jss633&quot;]/div[1]/nav[@class=&quot;MuiList-root sc-cvbbAY enFCrJ MuiList-padding&quot;]/div[@class=&quot;MuiBox-root jss638&quot;]/div[@class=&quot;MuiBox-root jss639&quot;]/div[@class=&quot;MuiBox-root jss647&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-view']/div/ui-view/section/md-content/md-content/ui-view/react-arba/div/div/div/div/div/div[3]/div/div/div/div/nav/div/div/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LISTREPORTS USER'])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mn.flores+1002@listreports.com'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marben Agent127'])[1]/preceding::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
