<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Create Marketing Kit</name>
   <tag></tag>
   <elementGuidId>7ea8b754-a933-410e-aefa-e6068d30e26b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>complete-user-profile-sref</name>
      <type>Main</type>
      <value>new-report</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>complete-user-profile-sref-params</name>
      <type>Main</type>
      <value>{ listing: vm.model.listing.id, source: vm.source, agentrelationship: vm.model.userRelationshipId, collapsedAgent: true }</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary btn-md</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{ 'btn-block': $mdMedia('xs') }</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>analytics-on</name>
      <type>Main</type>
      <value>click</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>analytics-event</name>
      <type>Main</type>
      <value>New ListReport Click</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>analytics-properties</name>
      <type>Main</type>
      <value>{
                                        Source: vm.source
                                    }</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>(vm.model.realtorPreferredTitleVendorId &amp;&amp; vm.model.realtorPreferredTitleVendorId !== vm.model.user.id) || (vm.model.realtorPreferredVendorId &amp;&amp; vm.model.realtorPreferredVendorId !== vm.model.user.id) || vm.model.addressVerified === false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Create Marketing Kit
                                </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/ui-view[@class=&quot;ng-scope&quot;]/view-listing[@class=&quot;ng-scope ng-isolate-scope&quot;]/section[@class=&quot;section layout-gt-xs-row layout-align-gt-xs-start-start&quot;]/div[@class=&quot;listing-info section-group flex-gt-xs&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;info-gallery layout-gt-sm-row&quot;]/div[@class=&quot;info flex-gt-xs&quot;]/div[@class=&quot;btn-wrap&quot;]/span[@class=&quot;ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/button[@class=&quot;btn btn-secondary btn-md&quot;]</value>
   </webElementProperties>
</WebElementEntity>
